Repository githubschool/california-dreaming, pull requests merged in 2022-02, with the labels that each got.

#16 Update kristymatsu's caption
  _slides/12-kristymatsu.md
Labels: documentation, enhancement

#10 Update andrewha288's slide caption
  _slides/08-andrewha288.md
Labels: good first issue

#15 Update vwlong's caption
  _slides/15-vwlong.md
Labels: documentation, enhancement

#9 Update rajGitSource's caption
  _slides/18-rajGitSource.md
Labels: documentation, enhancement

#12 Update caption
  _slides/04-AvaghAAA.md
Labels: enhancement

#20 Update dsanfor's caption
  _slides/09-dsanfor2.md
Labels: documentation, enhancement

#14 Update Solomon07in's caption
  _slides/14-solomon07in.md
Labels: documentation

#21 Update ragnaroken's caption
  _slides/13-ragnaroken.md
Labels: documentation, enhancement
